// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackendComputer.Models.Data
{
    public partial class Admin
    {
        public int Id { get; set; }
        public string AdminNme { get; set; }
        public string AdminPassword { get; set; }
    }
}