// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackendComputer.Models.Data
{
    public partial class DetailsProducts
    {
        public string Id { get; set; }
        public int? IdProductsDetails { get; set; }
        public string Image { get; set; }
        public string MoreDetail { get; set; }

        public virtual Products IdProductsDetailsNavigation { get; set; }
    }
}