// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackendComputer.Models.Data
{
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public int? IdOrder { get; set; }
        public int? IdProducts { get; set; }
        public int? Stock { get; set; }

        public virtual Order IdOrderNavigation { get; set; }
        public virtual Products IdProductsNavigation { get; set; }
    }
}