// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackendComputer.Models.Data
{
    public partial class StatusTransport
    {
        public StatusTransport()
        {
            Transport = new HashSet<Transport>();
        }

        public int Id { get; set; }
        public string Status { get; set; }

        public virtual ICollection<Transport> Transport { get; set; }
    }
}