// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackendComputer.Models.Data
{
    public partial class Stock
    {
        public int Id { get; set; }
        public int? IdProduct { get; set; }
        public int? Stock1 { get; set; }
        public string StockDate { get; set; }

        public virtual Products IdProductNavigation { get; set; }
    }
}