// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackendComputer.Models.Data
{
    public partial class Transport
    {
        public int Id { get; set; }
        public int? IdOrder { get; set; }
        public int? IdStatus { get; set; }
        public DateTime? Date { get; set; }

        public virtual Order IdOrderNavigation { get; set; }
        public virtual StatusTransport IdStatusNavigation { get; set; }
    }
}