// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackendComputer.Models.Data
{
    public partial class Type
    {
        public Type()
        {
            Products = new HashSet<Products>();
        }

        public int Id { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<Products> Products { get; set; }
    }
}