// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackendComputer.Models.Data
{
    public partial class User
    {
        public User()
        {
            Order = new HashSet<Order>();
        }

        public int Id { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public int? Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Tel { get; set; }
        public string UserAddress { get; set; }

        public virtual Title TitleNavigation { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}